name: Deploy to S3 Bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: mywebsitebucket-$(date +%s)
    steps:
    - uses: actions/checkout@v2
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    - name: Create S3 Bucket
      run: |
        aws s3api create-bucket --bucket $BUCKET_NAME --region $AWS_DEFAULT_REGION
    - name: Upload Website Files to S3 Bucket
      run: |
        aws s3 sync . s3://$BUCKET_NAME --region $AWS_DEFAULT_REGION