name: Deploy to S3 Bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: mywebsitebucket-$(date +%s)  
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::680324340095:role/githubdemo
        aws-region: us-east-1
    # - name: Rotate AWS Credentials
    #   run: |
    #     ./scripts/rotate-aws-credentials.sh
    - name: Create S3 Bucket
      run: |
        aws s3api create-bucket --bucket $BUCKET_NAME
    - name: Upload Website Files to S3 Bucket
      run: |
        aws s3 sync . s3://$BUCKET_NAME